all: fpu_imitate.h MIPSSimulator_main.cpp fpu_imitate.cpp Instruction.cpp ParseAndExecute.cpp MyType.cpp
	g++ -std=c++11 MIPSSimulator_main.cpp fpu_imitate.cpp  -o simulator_7 
clean:
	rm simulator_7 print* result.ppm 