# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/cpu/cpu/cpu.cache/wt [current_project]
set_property parent.project_path D:/cpu/cpu/cpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.6 [current_project]
set_property ip_output_repo d:/cpu/cpu/cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/cpu/cpu/team7-master/cons_grad_table2.mem
  D:/cpu/cpu/team7-master/sqrt_table.mem
}
read_verilog -library xil_defaultlib -sv {
  D:/cpu/cpu/alu.sv
  D:/cpu/cpu/aludec.sv
  D:/cpu/cpu/controller.sv
  D:/cpu/cpu/datapath.sv
  D:/cpu/cpu/dmem.sv
  D:/cpu/cpu/flopr.sv
  D:/cpu/cpu/fpudec.sv
  D:/cpu/cpu/hazard.sv
  D:/cpu/cpu/imem.sv
  D:/cpu/cpu/maindec.sv
  D:/cpu/cpu/mips.sv
  D:/cpu/cpu/mux2.sv
  D:/cpu/cpu/mux3.sv
  D:/cpu/cpu/regfile.sv
  D:/cpu/cpu/signext.sv
  D:/cpu/cpu/top.sv
  D:/cpu/cpu/uart_back.sv
  D:/cpu/cpu/uart_tx.sv
  D:/cpu/cpu/uart_rx.sv
}
read_verilog -library xil_defaultlib {
  D:/cpu/cpu/team7-master/fadd.v
  D:/cpu/cpu/team7-master/fdiv.v
  D:/cpu/cpu/team7-master/feq.v
  D:/cpu/cpu/team7-master/finv_p2.v
  D:/cpu/cpu/team7-master/fless.v
  D:/cpu/cpu/team7-master/floor.v
  D:/cpu/cpu/team7-master/fmul_undivided.v
  D:/cpu/cpu/team7-master/fpu.v
  D:/cpu/cpu/team7-master/fsqrt_p2.v
  D:/cpu/cpu/team7-master/ftoi.v
  D:/cpu/cpu/team7-master/inv_table.v
  D:/cpu/cpu/team7-master/itof.v
  D:/cpu/cpu/team7-master/sqrt_table.v
  D:/cpu/cpu/top_wrap.v
  D:/cpu/cpu/uart_back_wrap.v
  D:/cpu/cpu/uart_in.v
  D:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
add_files D:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/cpu/cpu/cpu.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/cpu/cpu/cpu.srcs/constrs_1/new/uart.xdc
set_property used_in_implementation false [get_files D:/cpu/cpu/cpu.srcs/constrs_1/new/uart.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xcku040-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
